name = "science-exam"
main = ".open-next/worker.js"
compatibility_date = "2026-10-06"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = true

[[routes]]
pattern = "onlinetest.bankruaschool.ac.th"
custom_domain = true

[vars]
NEXTAUTH_URL = "https://onlinetest.bankruaschool.ac.th"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "science-exam"

[[d1_databases]]
binding = "DB"
database_name = "science-exam-db"
database_id = "9bafff18-833f-40cc-81fe-4490d42052ba"

[[r2_buckets]]
binding = "R2"
bucket_name = "science-exam-files"
