name = "science-exam"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

main = ".vercel/output/static/_worker.js/index.js"

[assets]
directory = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "science-exam-db"
database_id = "9bafff18-833f-40cc-81fe-4490d42052ba"

[[r2_buckets]]
binding = "R2"
bucket_name = "science-exam-files"
