import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const banks = [
  ['science-p4', '4216d09b-d46a-5d6f-a54d-328f2d777444', [[40, 'แรงโน้มถ่วงและน้ำหนัก'], [70, 'ตัวกลางและแสง']]],
  ['science-p5', '12d95179-e0f7-5345-bbb3-0be297833378', [[50, 'เสียง'], [70, 'การเปลี่ยนแปลงของสาร']]],
  ['science-p6', '07bc635c-46e7-5c3c-a535-3c07fbec04b9', [[36, 'การแยกสาร'], [70, 'หินและซากดึกดำบรรพ์']]],
  ['science-m1', '64f0204a-6afc-44ba-bc35-d8354a1276cf', [[20, 'เซลล์และกล้องจุลทรรศน์'], [27, 'การลำเลียงสารผ่านเซลล์'], [46, 'การสร้างอาหารและลำเลียงในพืช'], [70, 'การสืบพันธุ์และขยายพันธุ์พืช']]],
  ['science-m2', 'a3f9b3c0-5846-4091-924f-7faa4ca70932', [[24, 'แรงและสนาม'], [40, 'แรงเสียดทาน'], [56, 'ความดันและแรงพยุง'], [70, 'การเคลื่อนที่']]],
  ['science-m3', 'bfc7b4ce-c8e7-488a-8335-bbc650262928', [[30, 'แสงและการมองเห็น'], [45, 'โลกและอวกาศ'], [70, 'พันธุกรรม']]],
  ['computing-m1', 'c0ed2277-edd8-435e-a36c-b412f5cb3bcc', [[22, 'อัลกอริทึมและแก้ปัญหา'], [40, 'ภาษา Python'], [50, 'Scratch'], [70, 'พัฒนาและทดสอบโปรแกรม']]],
  ['computing-m2', 'bdb3691c-c541-4f0b-b980-94fb7889a93b', [[6, 'ออกแบบขั้นตอน'], [16, 'ฟังก์ชัน'], [40, 'ข้อมูลและตัวดำเนินการ'], [53, 'ควบคุมการทำงาน'], [70, 'พัฒนาและทดสอบโปรแกรม']]],
  ['computing-m3', '98fd1113-8e0b-4643-8d26-f452b1e934ac', [[30, 'สืบค้นและแหล่งข้อมูล'], [38, 'ประเมินข้อมูล'], [47, 'เหตุผลและอคติ'], [60, 'พลเมืองดิจิทัล'], [70, 'ใช้ข้อมูลอย่างรับผิดชอบ']]],
];
const quote = value => `'${String(value).replaceAll("'", "''")}'`;
const sql = ['-- Generated by scripts/build-pools.mjs from reviewed TSV sources.'];
for (const [name, examId, topics] of banks) {
  const rows = readFileSync(resolve(root, `data/pool-${name}.tsv`), 'utf8').trim().split('\n').filter(line => !line.startsWith('#')).map(line => line.split('|').map(part => part.trim()));
  if (rows.length !== 70) throw new Error(`${name}: expected 70, got ${rows.length}`);
  const seen = new Set();
  rows.forEach(([question, correct, ...wrong], index) => {
    if (!question || wrong.length !== 3 || new Set([correct, ...wrong]).size !== 4 || [...[correct, ...wrong]].some(x => !x) || seen.has(question)) throw new Error(`${name}: invalid row ${index + 1}`);
    seen.add(question);
    const id = `pool-${name}-${index + 31}`;
    const topic = topics.find(([end]) => index + 1 <= end)[1];
    sql.push(`INSERT OR IGNORE INTO questions (id,exam_id,order_num,question_text,points,topic) VALUES (${quote(id)},${quote(examId)},${index + 31},${quote(question)},1,${quote(topic)});`);
    const correctIndex = index % 4;
    const options = [...wrong]; options.splice(correctIndex, 0, correct);
    options.forEach((text, i) => sql.push(`INSERT OR IGNORE INTO choices (id,question_id,order_num,choice_text,is_correct) VALUES (${quote(`${id}-c${i}`)},${quote(id)},${i + 1},${quote(text)},${i === correctIndex ? 1 : 0});`));
  });
  sql.push(`UPDATE exams SET description = 'คลังข้อสอบ 100 ข้อ เลือกจำนวนข้อและเวลาที่ใช้สอบได้' WHERE id = ${quote(examId)};`);
}
writeFileSync(resolve(root, 'migrations/0007_expand_question_pools.sql'), sql.join('\n') + '\n');
console.log('Validated and generated 630 questions / 2520 choices in 9 pools.');
